version: "3"
services:
  reverse-proxy:
    image: traefik:v2.9
    # Enables the web UI and tells Traefik to listen to docker
    command: --api.insecure=true --providers.docker
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  # App runner
  bsns_ems:
    build: ./
    labels:
      - "traefik.http.routers.bsns_ems.rule=Host(`medhead.localhost`) && PathPrefix(`/ems`)"
      - "traefik.http.routers.bsns_ems.middlewares=ems-stripprefix"
      - "traefik.http.middlewares.ems-stripprefix.stripprefix.prefixes=/ems"
      - "traefik.http.services.bsns_ems.loadbalancer.server.port=8080"

  # Redis dependency
  redis:
    image: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ./:/app